baseURL: "https://vishnuunk.github.io/"
languageCode: en-us
title: Vishnu Unnikrishnan
theme: PaperMod

menu:
  main:
    - identifier: home
      name: Home
      url: /
      weight: 10
    - identifier: projects
      name: Projects
      url: /projects
      weight: 20
    - identifier: blog
      name: Blog
      url: /blog
      weight: 30
    - identifier: skills
      name: Skills
      url: /skills
      weight: 40
    - identifier: resume
      name: Resume
      url: /files/resume.pdf
      weight: 50
    # - identifier: tags
    #   name: Tags
    #   url: /tags
    #   weight: 60
    # - identifier: notes
    #   name: Notes
    #   url: https://notes.arkalim.org
    #   weight: 70

params:
  # theme
  showToc: true
  TocOpen: false
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: true
  hideMeta: false

  # for enchanced SEO
  env: production

  # Home Page
  profileMode:
    enabled: true
    title: "Vishnu Unnikrishnan"
    subtitle: |
      First-Year Master's student studying Statistics at [**Department of Statistics, CUSAT**](https://stats.cusat.ac.in/). My interests are in Statistical Learning and Applied Data Science. Apart from this, I am also into Public Speaking. I completed my Bachelor's in Mathematics from [**St. Thomas College (Autonomous), Thrissur**](https://stthomas.ac.in/).

      Free free to drop an email!

 
    imageUrl: "home/formals-square.png"
    imageWidth: 220
    imageHeight: 220
    # buttons:
    #   - name: Resume
    #     url: ""

  # List View
  hideDescriptionInList: false

  # cover image for posts
  cover:
    hiddenInList: false # hide on list pages and home
    hiddenInSingle: false # hide on single page

  socialIcons:
    - name: "email"
      url: "mailto:vishnuunk@gmail.com"
    - name: "twitter"
      url: "https://x.com/getalifevishnu?s=21"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/vishnu-unnikrishnan-539504223/"
    - name: "github"
      url: "https://github.com/vishnuunk"
    

  # text search
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

# for search using Fuse.js
outputs:
  home:
    - HTML
    - RSS
    - JSON

# allow HTML in MD
markup:
  goldmark:
    renderer:
      unsafe: true
